# Generated by Django 2.2.12 on 2022-07-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('release', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('decription', models.TextField(max_length=250)),
            ],
        ),
    ]
