# Generated by Django 2.2.12 on 2022-07-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='decription',
            new_name='description',
        ),
    ]
